version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}

services:

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        - USERNAME=${USERNAME}
        - USER_UID=${USER_UID}
    container_name: nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    depends_on:
      - php-fpm
    networks:
      - backend

  php-fpm:
    build:
      context: .
      dockerfile: php-fpm.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - USERNAME=${USERNAME}
        - USER_UID=${USER_UID}
    container_name: php-fpm
    ports:
      - ${NGINX_PHP_UPSTREAM_PORT}:9000
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    networks:
      - backend

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      # It's important to recreate this folder `mysql` in /home/username/
      - mysql:/var/lib/mysql
    networks:
      - backend
        
  phpmyadmin:
    image: phpmyadmin:5.2-fpm-alpine
    container_name: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - backend
